### ISSUE TITLE
New patch uses ES6 Notation

### ISSUE THREAD

**Issue by jsyvino** [marcbachmann/simple-text-search#6]
the latest patch introduces const to the index.js file which causes issues with babel/webpack:

`Failed to minify the code from this file: 

 	./node_modules/simple-text-search/index.js:22 

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by marcbachmann** [comment]
Sorry for causing trouble with the breaking change.
By now almost all browsers support ES6 and also generators. Despite that it's still a pain in webpack to set it up properly, I won't change the code back.

Does transpiling cause any issues in your case?

**Comment by marcbachmann** [comment]
the new code got rid of the generator again some time ago
