### ISSUE TITLE
Is this a search Bug??

### ISSUE THREAD

**Issue by xurdep** [marcbachmann/simple-text-search#7]
First... Thank you for your work!!
Look at this small and sample code:

```
var query = 'Sidra Trabanco';
var data = ['Sidra Trabanco', 'Sidra Trabanco Selección', 'Sidra iSidra', 'Sidra Acebal'];
var get = filter(data);
console.info(get(query));

/*
RETURNS:
0: "Sidra Trabanco"
1: "Sidra Trabanco Selección"
2: "Sidra iSidra"

If I search text 'Trabanco', returns:

0: "Sidra Trabanco"
1: "Sidra Trabanco Selección"

Why???

I think 'Sidra iSidra' not match with the query...
*/
```
Thanks again!

**Comment by marcbachmann** [comment]
Yeah, with the latest change in https://github.com/marcbachmann/simple-text-search/commit/2e86556429af6d51224e3756cbeb31495d41f16f, the module is now directly using a regex for better performance.
With that change we don't need to loop through all the keywords for every single word. I assumed that this gives some performance boost, but sadly it also results in false positives.

Maybe I'll just change the logic again to use an `str.indexOf`.

**Comment by xurdep** [comment]
Hi!!
Thank you for your reply...
In my opinion, is better a bit of less performance than a false positives..
but is only my opinion...

If you'll rollback definetively I'll use this module, anyway a lot of
thanks.

Regards, xurdep

**Comment by marcbachmann** [comment]
A fix landed in #8

**Comment by marcbachmann** [comment]
As version [`1.1.3`](https://www.npmjs.com/package/simple-text-search)

**Comment by marcbachmann** [comment]
Hmmm. I guess I'll need another test for something. Found a bug. 🤦

**Comment by xurdep** [comment]
No worry...

All can wait...

💪🏻💪🏻

**Comment by marcbachmann** [comment]
FYI I've released [v1.1.4](https://github.com/marcbachmann/simple-text-search/releases) yesterday

**Comment by xurdep** [comment]
Hi @marcbachmann 

I just tested and works perfect! 

Thank you for your time, sir ;-)

**Comment by marcbachmann** [comment]
Nice, you're welcome

**Comment by marcbachmann** [comment]
Btw. I'm just wondering, are you using the module for mainly spanish or is the main locale some other language?

**Comment by xurdep** [comment]
I'm spanish, the project I'm working in is only in spanish language... sorry for my English ;-)
I would like to contact with you and ask you some questions, if you want, of course... I don't see your email but in my profile you can see mine... 
Best regards ;-)
